### PR TITLE
Bump next@13, react@18, cypress@12 and typescript@4.9

### PR DESCRIPTION
**Pull request by warizz**

### CODE REVIEW

**Comment by kylemh** [comment]
@warizz thanks so much! I'm thinking I'll put current `main` branch as `next-9thru12-cypress-under-v9` or something silly like that and make this `main` branch. I'll double check this branch to make sure coverage is still working.

**Comment by kylemh** [comment]
haven't forgotten this @warizz - i'll be tackling it at some point in the next 2 weeks.

**Comment by warizz** [comment]
@kylemh sure, no prob at all 😄 . Thanks for the update.

**Review by kylemh — APPROVED** [review]
By 2 weeks, I meant 3 😂 

I did one last `yarn upgrade-interactive --latest` to freshen things up since it took me so long. I also made https://github.com/kylemh/next-ts-with-cypress-coverage/tree/next9thru12-and-cypress5thru9 and updated the README!

Thanks for doing the hard work of converting the Cypress code!

**Pull request merged**
